version: "2"

services:
  db:
    image: postgres:9.5.3
    command: postgres -F

  messybrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.test
    image: web
    depends_on:
      - db

  redis:
    image: redis:3.2.1

