version: "3.4"

# IMPORTANT NOTE: Volume paths mounted on containers are relative to the
# directory that this file is in (`docker/`) and so probably need to start with
# `../` to refer to a directory in the main code checkout

volumes:
  couchdb:

services:

  couchdb:
    image: couchdb:3.2.2
    environment:
      COUCHDB_USER: listenbrainz
      COUCHDB_PASSWORD: listenbrainz
    ports:
      - "127.0.0.1:5984:5984" 
    volumes:
      - ./couchdb.ini:/opt/couchdb/etc/local.ini
      - couchdb:/opt/couchdb/data
