scanner:
  diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
  linter: pycodestyle  # Other option is flake8

pycodestyle:  # Same as scanner.linter value. Other option is flake8
  max-line-length: 130  # Default is 79 in PEP 8

no_blank_comment: True  # If True, no comment is made on PR without any errors.