version: '2'
services:
  db:
    image: postgres:9.5.3
    volumes:
       - ./pgdata:/pgdata
    environment:
       PGDATA: /pgdata
       POSTGRES_USER: listenbrainz
       POSTGRES_PASSWD: listenbrainz
       POSTGRES_DB: listenbrainz
  redis:
    image: redis:3.2.1
    volumes:
      - ./data/redis:/data
  web:
    build: .
    command: python manage.py runserver -h 0.0.0.0 -p 8000
    volumes:
      - .:/code/listenbrainz-server
      - ./data/app:/data
    ports:
      - "8000:8000"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
  consumer:
    build: 
      dockerfile: redis-consumer/Dockerfile
      context: .
    command: python redis-consumer/redis-consumer.py
    volumes:
      - .:/code/listenbrainz-server
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
