version: '2'
services:
  redis:
    image: redis
  kafka:
    image: spotify/kafka
  web:
    build: .
    command: dockerize -wait tcp://kafka:9092 python manage.py runserver -h 0.0.0.0 -p 8000
    volumes:
      - .:/code/listenbrainz-server
      - ./data/app:/data
    ports:
      - "8000:8000"
    links:
      - kafka
    depends_on:
      - redis
      - kafka
