version: '2'
services:
  db:
    image: postgres:9.5.3
    volumes:
       - ./pgdata:/pgdata
    environment:
       PGDATA: /pgdata
       POSTGRES_USER: listenbrainz
       POSTGRES_PASSWD: listenbrainz
       POSTGRES_DB: listenbrainz
  redis:
    image: redis
  web:
    build: .
    command: python manage.py runserver -h 0.0.0.0 -p 8000
    entrypoint: python redis-consumer.py
    volumes:
      - .:/code/listenbrainz-server
      - ./data/app:/data
    ports:
      - "8000:8000"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
