version: "2"
services:

  db:
    image: postgres:9.5.3
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: listenbrainz
      POSTGRES_PASSWD: listenbrainz
      POSTGRES_DB: listenbrainz
    restart: always

  redis:
    image: redis:3.2.1
    volumes:
      - ./data/redis:/data
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: uwsgi /code/listenbrainz-server/docker/uwsgi.ini
    volumes:
      - .:/code/listenbrainz-server
      - ./data/app:/data
    ports:
      - "3031:3031"
    depends_on:
      - redis
      - db
    restart: always

  consumer:
    build: 
      dockerfile: redis-consumer/Dockerfile
      context: .
    command: python redis-consumer/redis-consumer.py
    volumes:
      - .:/code/listenbrainz-server
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    extends:
      file: ./docker/common.yml
      service: nginx
    links:
      - web
    restart: always
