# Docker Compose file with common services
# See https://docs.docker.com/compose/extends/#extending-services
version: "2"
services:

  nginx:
    restart: always
    build:
      context: ./nginx_custom/
      dockerfile: Dockerfile
    ports:
      - "80:80"
