version: "2"
services:

  db:
    image: postgres:9.5.3
    volumes:
      - $DATA_DIR/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: listenbrainz
      POSTGRES_PASSWD: listenbrainz
      POSTGRES_DB: listenbrainz
    restart: always

  redis:
    image: redis:3.2.1
    volumes:
      - $DATA_DIR/data/redis:/data
    restart: always

  influx:
    image: influxdb:0.13.0
    volumes:
      - $DATA_DIR/data/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: 'true'
      INFLUXDB_META_LOGGING_ENABLED: 'false'
      INFLUXDB_DATA_QUERY_LOG_ENABLED: 'false'
      INFLUXDB_DATA_WAL_LOGGING_ENABLED: 'false'
      INFLUXDB_DATA_DATA_LOGGING_ENABLED: 'false'
      INFLUXDB_HTTP_LOG_ENABLED: 'true'
      INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED: 'false'

    ports:
      - "8086:8086"
      - "8083:8083"
    restart: always

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: uwsgi /code/listenbrainz/docker/uwsgi.ini
    volumes:
      - $DATA_DIR/data/app:/data
    ports:
      - "3031:3031"
    depends_on:
      - redis
      - db
      - influx
    restart: always

  influx_writer:
    build:
      context: ..
      dockerfile: ./docker/influx-writer/Dockerfile
    command: python influx-writer/influx-writer.py
    depends_on:
      - redis
      - influx
    restart: always

  bigquery:
    build:
      context: ..
      dockerfile: ./docker/bigquery-writer/Dockerfile
    command: python bigquery-writer/bigquery-writer.py
    depends_on:
      - redis
    restart: always

  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - web
    restart: always
