FROM python:2.7.12

ENV DOCKERIZE_VERSION v0.2.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
                       build-essential \
                       redis-tools \
                       git \
                       wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uWSGI==2.0.13.1

# PostgreSQL client
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
ENV PG_MAJOR 9.5
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list
RUN apt-get update \
    && apt-get install -y postgresql-client-$PG_MAJOR \
        && rm -rf /var/lib/apt/lists/*

# Specifying password so that client doesn't ask scripts for it...
ENV PGPASSWORD "listenbrainz"

RUN mkdir /code
WORKDIR /code

# MessyBrainz
RUN git clone https://github.com/metabrainz/messybrainz-server.git messybrainz
WORKDIR /code/messybrainz
RUN pip install -r requirements.txt
RUN python setup.py install

RUN mkdir /code/listenbrainz
WORKDIR /code/listenbrainz

COPY requirements.txt /code/listenbrainz/
RUN pip install -r requirements.txt

COPY . /code/listenbrainz/
COPY config_test.py /code/listenbrainz/config.py

RUN mkdir /data

CMD dockerize -wait tcp://db_test:5432 -timeout 60s \
              -wait tcp://influx_test:8086 -timeout 60s \
            python manage.py init_db && python manage.py init_msb_db --create-db && python admin/influx/create_db.py && py.test
