version: "2"

services:
  db:
    image: postgres:9.5.3

  messybrainz:
    build:
      context: ..
      dockerfile: Dockerfile
    command: bash -c "cd /code/messybrainz && pwd && ls -lR && cp config.py.sample config.py && py.test --junitxml=/data/test_report.xml --cov-report xml:/data/coverage.xml"
    image: web
    depends_on:
      - db

  redis:
    image: redis:3.2.1

