version: "2"
services:

  db:
    image: postgres:9.5.3
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: listenbrainz
      POSTGRES_PASSWD: listenbrainz
      POSTGRES_DB: listenbrainz
    restart: always

  redis:
    image: redis:3.2.1
    volumes:
      - ../data/redis:/data
    restart: always

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.prod
    command: uwsgi /code/listenbrainz/docker/uwsgi.ini
    volumes:
      - ../data/app:/data
    ports:
      - "3031:3031"
    depends_on:
      - redis
      - db
    restart: always

  consumer:
    build:
      context: ..
      dockerfile: ./docker/redis-consumer/Dockerfile
    command: python redis-consumer/redis-consumer.py
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - web
    restart: always
