version: "3.4"

services:

  namenode:
    build:
      context: ..
      dockerfile: Dockerfile.spark
      args:
        GIT_COMMIT_SHA: HEAD
    image: metabrainz-spark-test
    command: bash -c "hdfs namenode -format && hdfs namenode"
    expose:
      - "9000"
      - "9870"

  datanode:
    image: metabrainz-spark-test
    command: bash -c "hdfs datanode"
    depends_on:
      - namenode

  spark:
    image: metabrainz-spark-test
    depends_on:
      - namenode
      - datanode
    command: dockerize -wait tcp://namenode:9000 -timeout 60s bash -c "cp listenbrainz_spark/config.py.sample listenbrainz_spark/config.py; PYTHONDONTWRITEBYTECODE=1 python -m pytest -c pytest.spark.ini"
    volumes:
      - ..:/rec
