version: "3.4"

services:

  test:
    build:
      context: ..
      dockerfile: Dockerfile.spark
      args:
         GIT_COMMIT_SHA: HEAD
    command: bash -c "cp listenbrainz_spark/config.py.sample listenbrainz_spark/config.py; PYTHONDONTWRITEBYTECODE=1 python -m pytest -c pytest.spark.ini"
    volumes:
      - ..:/rec
