version: "3.4"

volumes:
    datanode:
    namenode:

services:
  hadoop-master:
    image: metabrainz/hadoop-yarn:beta
    command: hdfs namenode
    volumes:
      - namenode:/home/hadoop/hdfs:z
    ports:
      - "9000:9000"
      - "9870:9870"

  datanode:
    image: metabrainz/hadoop-yarn:beta
    command: hdfs datanode
    volumes:
      - datanode:/home/hadoop/hdfs:z

  test:
    build:
      context: ..
      dockerfile: Dockerfile
      target: metabrainz-spark-dev
    command: dockerize -wait tcp://hadoop-master:9000 -timeout 60s bash -c "cp listenbrainz_spark/config.py.sample listenbrainz_spark/config.py; python -m pytest --junitxml=/data/test_report.xml --cov-report xml:/data/coverage.xml"
