#!/bin/bash
# In consul-template's exec mode (https://github.com/hashicorp/consul-template/blob/master/docs/modes.md#exec-mode)
# subprocesses do not run in a shell, so we use this wrapper script to correctly set the working directory
# and then exec to the desired process. We use exec so that signals are passed to the process correctly.

. /etc/lb-startup-common.sh

cd /code/listenbrainz

log run-lb-command starting "$@"

# we grep config files rendered by consul to check for missing keys/services
for config_file in listenbrainz/config.py clickhouse/config.py; do
  if [ ! -f "$config_file" ]; then
    continue
  fi

  keyerrors=$(grep KEYDOESNOTEXIST "$config_file")
  if [ -n "$keyerrors" ]; then
    log "Found keys that are missing from consul in $config_file"
    echo "$keyerrors"
    log "Config file is as follows"
    cat "$config_file"
    exit 10
  fi
  serviceerrors=$(grep SERVICEDOESNOTEXIST "$config_file")
  if [ -n "$serviceerrors" ]; then
    log "Found services that are missing from consul in $config_file"
    echo "$serviceerrors"
    log "Config file is as follows"
    cat "$config_file"
    exit 11
  fi
done

exec "$@"
