BEGIN;

CREATE TYPE entity_recommendation_type AS ENUM ('artist', 'release_group', 'release', 'recording');

CREATE TABLE recommendation.entity_recommendation (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         INTEGER NOT NULL,
    source_entity_type  entity_recommendation_type NOT NULL,
    source_entity_mbid  UUID NOT NULL,
    target_entity_type  entity_recommendation_type NOT NULL,
    target_entity_mbid  UUID NOT NULL,
    specificity_score   SMALLINT NOT NULL,
    blurb           TEXT,
    created         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE recommendation.entity_recommendation
    ADD CONSTRAINT entity_recommendation_pkey PRIMARY KEY (id);

ALTER TABLE recommendation.entity_recommendation
    ADD CONSTRAINT entity_recommendation_user_id_foreign_key
    FOREIGN KEY (user_id)
    REFERENCES "user" (id)
    ON DELETE CASCADE;

CREATE UNIQUE INDEX user_src_tgt_ndx_entity_recommendation
    ON recommendation.entity_recommendation (user_id, source_entity_type, source_entity_mbid, target_entity_type, target_entity_mbid);

CREATE INDEX src_entity_ndx_entity_recommendation
    ON recommendation.entity_recommendation (source_entity_type, source_entity_mbid);

CREATE INDEX specificity_score_ndx_entity_recommendation
    ON recommendation.entity_recommendation (specificity_score DESC);

COMMIT;
