name             "basebox"
maintainer       "YOUR_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures basebox"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version "0.1.1"
depends          "apt"
depends          "chef-client"
depends          "sudo"
depends          "users"
depends          "timezone-ii"
depends          "sysctl"
depends          "fail2ban"
depends          "ntp"
depends          "ssh_known_hosts"
depends          "hostsfile"
