server {
    listen 80;
    server_name proxy.listenbrainz.org;
    root /usr/share/nginx/html;
    location /static/dist/ {
        alias /static/dist/;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }
    location /static/img/ {
        alias /static/img/;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }
    location /static/ {
        alias /static/;
        try_files $uri =404;
    }
    location / {
        try_files $uri @wsgi;
    }
    location @wsgi {
        include uwsgi_params;
        uwsgi_pass 10.2.2.45:13037;
    }
}
