template {
    source = "/code/listenbrainz/clickhouse/consul_config.py.ctmpl"
    destination = "/code/listenbrainz/clickhouse/config.py"
}

exec {
    command = ["run-lb-command", "python3", "-m", "clickhouse.request_consumer"]
    splay = "5s"
    # Do not restart this worker when consul re-renders clickhouse/config.py.
    reload_signal = "SIGCONT"
    kill_signal = "SIGTERM"
    kill_timeout = "30s"
}
