# Single node Garage setup for local development and tests. Do not use in production.
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "b8f1a1a4c8d94e4db0f8b1b0a0d8f5e2a7c3b9d1e4f60718293a4b5c6d7e8f90"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "listenbrainz-dev-admin-token"
