name: Build and publish image to Docker Hub

on:
  release:
    types: [published]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Pull latest docker image
      run: docker pull metabrainz/listenbrainz:latest
      continue-on-error: true

    - name: Build and push image
      # Github stores the current tag in an enviroment variable (GITHUB_REF) in the format /refs/tags/TAG_NAME.
      # Using shell parameter expansion, we extract the TAG_NAME.
      run: ./docker/push.sh "${GITHUB_REF/refs\/tags\//}"
