name: Build and publish image to Docker Hub

on:
  release:
    types: [published]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.3.0
      
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        build-args: GIT_COMMIT_SHA=${{ github.sha }}
        cache-from: kartik1712/listenbrainz:cache
        cache-to: kartik1712/listenbrainz:cache
        push: true
        # Github stores the current tag in an enviroment variable (GITHUB_REF) in the format /refs/tags/TAG_NAME.
        # Using shell parameter expansion, we extract the TAG_NAME.
        tags: kartik1712/listenbrainz:${GITHUB_REF/refs\/tags\//}
        target: listenbrainz-prod
