# This workflow can be used to push an image off a branch to Docker Hub.
# This is useful to deploy changes to LB beta or test for testing.
name: Push development image

on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR number (if set, ignores above ^)'
        required: false
        type: string
      tag:
        description: 'Docker Image Tag (Version)'
        required: true
        default: 'beta'

jobs:

  dev:

      runs-on: ubuntu-latest

      steps:
      # Run only if we are deploying a branch or tag from this repo
      - uses: actions/checkout@v4
        # empty strings evaluate to 0
        if: ${{ github.event.inputs.pr == 0}}
        
      # Run only if we are deploying a PR (may be in a forked repo)
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.pr != 0}}
        with:
          ref: ${{ format('refs/pull/{0}/head', github.event.inputs.pr) }}


      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        continue-on-error: true

      - name: Build development image
        run: |
          docker build \
            --target listenbrainz-prod \
            --tag metabrainz/listenbrainz:"${{ github.event.inputs.tag }}" \
            --build-arg GIT_COMMIT_SHA="${{ github.sha }}" .

      - name: Push development image
        run: docker push metabrainz/listenbrainz:"${{ github.event.inputs.tag }}"
